config/routes.rb
Rails.application.routes.draw do
  resources :entries
  root 'monsters#home'
  resources :body_parts
  resources :monsters, except: [:edit]
  resources :beauty_contests
  resources :users, except: [:edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/monsters/:id/like', to: 'users#like', as: 'like'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :user
  belongs_to :face, class_name: 'BodyPart', foreign_key: :face_id, optional: true
  belongs_to :head, class_name: 'BodyPart', foreign_key: :head_id, optional: true
  belongs_to :torso, class_name: 'BodyPart', foreign_key: :torso_id, optional: true
  belongs_to :leg, class_name: 'BodyPart', foreign_key: :leg_id, optional: true
  has_many :likes
  has_one :entry
  
  validates :name, presence: true, uniqueness: true

  def mood
    case self.happiness
    when 0..2
      "angry"
    when 3..5
      "sad"
    when 6..10
      "happy"
    else
      "happy"
    end
  end

  def age
    ((Time.zone.now - self.created_at) / (60*60*24)).to_i + 1
  end

  def height
    top = 0
    ys = {}

    # Get min/max y to calculate the height
    if self.head_id
      ys[:head] = self.head_y
    end

    if self.torso_id
      ys[:torso] = self.torso_y
    end

    if self.leg_id
      ys[:leg] = self.leg_y
    end

    min_y = ys.values.min
    max_y = ys.values.max
    max_section = ys.key(max_y)

    case max_section
    when "head"
      max_y += 200 * head_scale_y
    when "torso"
      max_y += 200 * torso_scale_y
    when "leg"
      max_y += 200 * leg_scale_y
    end

    max_y - min_y
  end

  def weight
    weight = 0

    if self.head_id
      weight += 10 * self.head_scale
    end

    if self.torso_id
      weight += 20 * self.torso_scale
    end

    if self.leg_id
      weight += 15 * self.leg_scale
    end

    (weight - self.name.length/5.0).round(2)
  end

  def get_hours_since_last_fed
    (Time.zone.now - self.time_last_fed) / (60 * 60)
  end

  def update_happiness
    case get_hours_since_last_fed
    when 0..24
      self.happiness = (16 - get_hours_since_last_fed/3).clamp(0, 10)
    when 25..36
      self.happiness = (15 - get_hours_since_last_fed/3 ).clamp(0, 10)
    when get_hours_since_last_fed > 37
      self.happiness = (14 - get_hours_since_last_fed/3).clamp(0, 10)
    end
  end

  private

  def clamp(min, max)
    [[self, max].min, min].max
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  skip_before_action :authenticate_user, only: [:index, :home, :show]
  before_action :set_monster, only: [:show, :update, :destroy]
  before_action :set_body_parts, only: [:new]

  def index
    @monsters = Monster.all
  end

  def show
    user = User.find_by(id: session[:user_id]) 
    @is_user_owner = user && @monster.user.id == user.id
    @has_user_liked = user && Like.find_by(user_id: user.id, monster_id: @monster.id)
    @monster.update_happiness if @monster.time_last_fed
  end

  def new
    # Default values
    @monster = Monster.new(
      face_id: @faces.sample.id,
      face_x: 400/3,
      face_y: 9,
      face_scale: 1.0,

      head_id: @heads.sample.id,
      head_x: 400/3,
      head_y: 0,
      head_scale: 1.0,

      torso_id: @torsos.sample.id,
      torso_x: 400/3,
      torso_y: 360/3,
      torso_scale: 1.0,

      leg_id: @legs.sample.id,
      leg_x: 400/3,
      leg_y: 759/3,
      leg_scale: 1.0,
    )
  end


  def create
    user = User.find_by(id: session[:user_id])
    @monster = user.monsters.build(monster_params)
    
    if @monster.save
      @monster.update(happiness: 10, time_last_fed: Time.zone.now)
      redirect_to @monster
    else
      render :new
    end
  end

  def update
    if (monster_params[:time_last_fed])
      flash[:overfed] = (@monster.time_last_fed - Time.parse(monster_params[:time_last_fed])) / 3600 < 24

      # Gain weight
      if flash[:overfed]
        @monster.update(
          head_scale: @monster.head_scale * 1.001,
          torso_scale: @monster.torso_scale * 1.001,
          leg_scale: @monster.leg_scale * 1.001
        )
      end

      # Update happiness if fed
      @monster.update_happiness 
    end

     if @monster.update(monster_params)
       redirect_to @monster
    # else
    #   render :edit
     end
  end

  def destroy
    @monster.destroy
    redirect_to root_path
  end

  def home
  end

  private

  def monster_params
    params.require(:monster).permit!
  end

  def set_monster
    @monster = Monster.find(params[:id])
  end

  def set_body_parts
    @faces = BodyPart.where(section: "face")
    @heads = BodyPart.where(section: "head")
    @torsos = BodyPart.where(section: "torso")
    @legs = BodyPart.where(section: "leg")
  end
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/monsters/_card.erb
<div class="card" style="width: 200px">
  <span style="border-bottom: 1px solid rgba(0,0,0,0.25)">
    <%= link_to monster, :action => 'go' do %>
      <div class="card-portrait">
      <%= render partial: "monsters/portrait", locals: {monster: monster, size: 'small', draggable: false} %>
      </div>
    <% end %>
  </span>
  <div class="card-body">
    <%= link_to monster, :action => 'go' do %><h5 class="card-title"><%= monster.name %></h5><% end %>
    <%= link_to monster.user, :action => 'go' do %><h6 class="card-subtitle mb-2 text-muted"><%= monster.user.name %></h6><%end%>
    <% if monster.has_won_contest %>
      <span style="float: left" title="Contest Winner">
        <%= octicon "star", height: '24', fill: 'orange' %>
      </span>
    <% end %>
    <span style="float: right">
      <%= octicon "heart", height: '24', fill: 'red' %>&nbsp;<%= Like.where(monster_id: monster.id).size %>
    </span>
  </div>
</div>

app/views/monsters/_form.erb
<%= form_for(@monster) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <div class="forms">
    <div class="form-block">
      <%= f.label :face_id, "Face" %>
      <%= f.collection_select :face_id, BodyPart.where(section: "face"), :id, :filename %><br>
      <%= f.hidden_field :face_x %>
      <%= f.hidden_field :face_y %>
      <%= f.hidden_field :face_scale %>
      <%= f.label :face_scale, "Scale" %>
      <div id="face_scale" class="slider" ></div>
      <br>
    </div>
    <div class="form-block">
      <%= f.label :head_id, "Head" %>
      <%= f.collection_select :head_id, BodyPart.where(section: "head"), :id, :filename %><br>
      <%= f.hidden_field :head_x %>
      <%= f.hidden_field :head_y %>
      <%= f.hidden_field :head_scale %>
      <%= f.label :head_scale, "Scale" %>
      <div id="head_scale" class="slider" ></div>
      <br>
    </div>

    <div class="form-block">
      <%= f.label :torso_id, "Torso" %>
      <%= f.collection_select :torso_id, BodyPart.where(section: "torso"), :id, :filename %><br>
      <%= f.hidden_field :torso_x %>
      <%= f.hidden_field :torso_y %>
      <%= f.hidden_field :torso_scale %>
      <%= f.label :torso_scale, "Scale" %>
      <div id="torso_scale" class="slider" ></div>
      <br>
    </div>

    <div class="form-block">
      <%= f.label :leg_id, "Leg" %>
      <%= f.collection_select :leg_id, BodyPart.where(section: "leg"), :id, :filename %><br>
      <%= f.hidden_field :leg_x %>
      <%= f.hidden_field :leg_y %>
      <%= f.hidden_field :leg_scale %>
      <%= f.label :leg_scale, "Scale" %>
      <div id="leg_scale" class="slider" ></div>
      <br>
    </div>
  </div>
  <%= f.submit 'Create Monster'%>
<% end %>

app/views/monsters/_portrait.erb
  <div class="monster-canvas center <%= size %>">
  <img
    id="face"
    class="body-part face <%= "draggable" if draggable %>"
    style="
      left: <%= size == "small" ? monster.face_x/2 : monster.face_x %>px;
      top: <%= size == "small" ? monster.face_y/2 : monster.face_y %>px;
      -webkit-transform : scale(<%= monster.face_scale %>);
      -moz-transform    : scale(<%= monster.face_scale %>);
      -ms-transform     : scale(<%= monster.face_scale %>);
      -o-transform      : scale(<%= monster.face_scale %>);
      transform         : scale(<%= monster.face_scale %>);
    "
    src="<%= asset_path("faces/#{monster.face.filename}.svg") %>"
  />
  <img
    id="head"
    class="body-part head <%= "draggable" if draggable %>"
    style="
      left: <%= size == "small" ? monster.head_x/2 : monster.head_x %>px;
      top: <%= size == "small" ? monster.head_y/2 : monster.head_y %>px;
      -webkit-transform : scale(<%= monster.head_scale %>);
      -moz-transform    : scale(<%= monster.head_scale %>);
      -ms-transform     : scale(<%= monster.head_scale %>);
      -o-transform      : scale(<%= monster.head_scale %>);
      transform         : scale(<%= monster.head_scale %>);
    "
    src="<%= asset_path("heads/#{monster.head.filename}.svg") %>"
  />
  <img
    id="torso"
    class="body-part torso <%= "draggable" if draggable %>"
    style="
      left: <%= size == "small" ? monster.torso_x/2 : monster.torso_x %>px;
      top: <%= size == "small" ? monster.torso_y/2 : monster.torso_y %>px;
      -webkit-transform : scale(<%= monster.torso_scale %>);
      -moz-transform    : scale(<%= monster.torso_scale %>);
      -ms-transform     : scale(<%= monster.torso_scale %>);
      -o-transform      : scale(<%= monster.torso_scale %>);
      transform         : scale(<%= monster.torso_scale %>);
    "
    src="<%= asset_path("torsos/#{monster.torso.filename}.svg") %>"
  />
  <img
    id="leg"
    class="body-part leg <%= "draggable" if draggable %>"
    style="
      left: <%= size == "small" ? monster.leg_x/2 : monster.leg_x %>px;
      top: <%= size == "small" ? monster.leg_y/2 : monster.leg_y %>px;
      -webkit-transform : scale(<%= monster.leg_scale %>);
      -moz-transform    : scale(<%= monster.leg_scale %>);
      -ms-transform     : scale(<%= monster.leg_scale %>);
      -o-transform      : scale(<%= monster.leg_scale %>);
      transform         : scale(<%= monster.leg_scale %>);
    "
    src="<%= asset_path("legs/#{monster.leg.filename}.svg") %>"
  >
</div>

app/views/monsters/edit.erb
<div class="container">
  <h1>Edit <%= @monster.name %></h1>
  <div class="row">
    <div class="col-md">
      <%= render partial: "form", locals: {monster: @monster} %>
    </div>

    <div class="col-md">
      <%= render partial: "portrait", locals: {monster: @monster, size: 'large', draggable: true} %>
    </div>
  </div>
</div>

app/views/monsters/home.erb
<div class="home-page">
  <div class="container">
    <h1 class="display-4 top-padding">Monster Mash</h1>
    <p class="lead">Mix and match different monster body parts to create your own monster!</p>
    <div class="col-md-4">
      <%= link_to "View Monsters", monsters_path, class: "btn btn-lg btn-secondary btn-block" %>
  </div>

app/views/monsters/index.erb
<div class="container">
<h1>All Monsters</h1>
  <div class="row content-scroll">
  <% @monsters.each do |monster| %>
    <div class="col-md-3">
      <%= render partial: "card", locals: {monster: monster} %>
    </div>
  <% end %>
  </div>
</div>

app/views/monsters/new.erb
<div class="container">
  <h1>Create New Monster</h1>

  <% if @monster.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <%= @monster.errors.full_messages.first %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md">
      <%= render partial: "form", locals: {monster: @monster} %>
    </div>

    <div class="col-md">
      <div class="preview-container">
        <%= render partial: "portrait", locals: {monster: @monster, size: 'large', draggable: true} %>
      </div>
    </div>
  </div>
</div>

app/views/monsters/show.erb
<div class="container monsters-show">
  <div class="row">
    <div class="col-md">
      <div class="card">
        <div class="card-header">
          <h1><%= @monster.name %></h1>
        </div>
        <div class="card-body">
          <p>Age: <%= pluralize(@monster.age, "day") %> old</p>
          <p>Weight: <%= @monster.weight %>kg</p>
          <p>Height: <%= @monster.height %>cm</p>
          <p>Mood: <%= @monster.mood %></p>
        </div>
        <div class="card-body">
          <span style="float: left">
            <% if @is_user_owner %>
              <%= form_for @monster do |f| %>
                <%= f.hidden_field :time_last_fed, value: Time.zone.now %>
                <button type="submit" name="commit" class="btn btn-md btn-primary">
                  <span class="icon-button">
                    <%= octicon "squirrel", fill: 'white' %>&nbsp;&nbsp;Feed
                  </span>
                </button>
              <% end %>
            <% end %>
            <%= form_tag like_path do %>
              <% if !@is_user_owner %>
                <% if !@has_user_liked %>
                  <%= hidden_field_tag name="do_like" %>
                  <button type="submit" name="commit" class="btn btn-md btn-outline-danger">
                    <span class="icon-button">
                      <%= octicon "heart", fill: 'red' %>&nbsp;&nbsp;Like&nbsp;
                    </span>
                  </button>
                <% else %>
                  <button type="submit" name="commit" class="btn btn-md btn-danger">
                    <span class="icon-button" style="color: white">
                      <%= octicon "heart", fill: 'white' %>&nbsp;&nbsp;Liked
                    </span>
                  </button>
                <%end %>
              <% end %>
            <% end %>
          </span>
          <span style="line-height: 55px; float: right">
            <%= octicon "heart", :height => 32, fill: 'red' %>&nbsp;<%= Like.where(monster_id: @monster.id).size %>
          </span>
        </div>

      </div>
    </div>
    <div class="col-md">
        <%= render partial: "portrait", locals: {monster: @monster, size: 'large', draggable: false} %>
    </div>
  </div>
  <% if flash[:overfed] %>
    <div class="alert alert-warning" role="alert">
      You fed <%= @monster.name %> today.
    </div>
  <% end %>
</div>