config/routes.rb
Rails.application.routes.draw do
  resources :entries
  root 'monsters#home'
  resources :body_parts
  resources :monsters, except: [:edit]
  resources :beauty_contests
  resources :users, except: [:edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/monsters/:id/like', to: 'users#like', as: 'like'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonsterMash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Baloo+Chettan|Bowlby+One+SC|Londrina+Solid" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.1/css/mdb.min.css" />
   
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <link rel='icon' href='/favicon.ico'/>
  </head>


  <nav class="navbar fixed-top navbar-expand-lg navbar-light nav-bar-color fixed-top">
    <div class="container">
      <%= link_to image_tag("logo.svg", alt: "logo"), '/', class: 'navbar-brand' %>
      <a class="navbar-brand" href="/">Monster Mash</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
          <li class="nav-item"> <%= link_to "Create Monster", new_monster_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= link_to "Monsters", monsters_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= link_to "Contests", beauty_contests_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= link_to "My Profile", user_path(User.find_by(id: session[:user_id])), class: "nav-link" %></li>
          <li class="nav-item"> <%= link_to "Log Out", logout_path, class: "nav-link", method: 'delete'%></li>
          <% else %>
          <li class="nav-item"> <%= link_to "Monsters", monsters_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= link_to "Log In", login_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <body>
    <div class="page">
      <%= yield %>
    </div>
  </body>
</html>